In [1]:
import pandas as pd
from scipy.spatial import distance
import numpy as np

In [2]:
feat = pd.read_csv(r'C:\Users\lttso\Desktop\feature_task.csv')

In [3]:
conj = pd.read_csv(r'C:\Users\lttso\Desktop\conjunction_task.csv')

In [4]:
feat['run_length'] = feat['runLength'] - 1
feat['run_length'] = feat['run_length'].shift(1)
feat = feat[feat['run_length'].notna()]

In [5]:
feat

,participantN,age,gender,trialN,task,condition,FeatConj,setSize,proportion,timelimit,...,closest_other_taget,closest_blue_dot,closest_yellow_dot,group_selected,group_same,group_switch,strict_line,blocked_grouped,ratio,run_length
1,1,0,,1,0,r/g,0,80,50,0.0,...,"[799.64, 503.31]","[879.51, 645.87]","[878.19, 441.13]",0,0,0,0,0,-0.043466,0.0
2,1,0,,1,0,r/g,0,80,50,0.0,...,"[799.64, 503.31]","[727.41, 563.11]","[646.05, 580.26]",0,0,0,1,0,-0.066947,1.0
3,1,0,,1,0,r/g,0,80,50,0.0,...,"[792.03, 570.48]","[879.51, 645.87]","[646.05, 580.26]",0,0,0,0,0,0.066947,2.0
4,1,0,,1,0,r/g,0,80,50,0.0,...,"[651.08, 650.09]","[727.41, 563.11]","[646.05, 580.26]",0,0,0,0,0,0.045757,0.0
5,1,0,,1,0,r/g,0,80,50,0.0,...,"[700.55, 659.76]","[727.41, 563.11]","[646.05, 580.26]",0,0,0,1,0,-0.048305,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13195,133,0,NaN,11,0,r/g,0,80,50,0.0,...,"[733.64, 271.54]","[634.7, 333.35]","[795.52, 261.99]",0,0,0,0,0,0.124939,0.0
13196,133,0,NaN,11,0,r/g,0,80,50,0.0,...,"[749.13, 400.0]","[904.86, 353.12]","[826.02, 432.72]",0,0,0,0,0,0.000000,0.0
13197,133,0,NaN,11,0,r/g,0,80,50,0.0,...,"[750.67, 661.48]","[799.22, 494.15]","[723.19, 510.42]",0,0,0,0,0,-0.176091,1.0
13198,133,0,NaN,11,0,r/g,0,80,50,0.0,...,"[788.75, 553.83]","[872.5, 595.98]","[723.19, 510.42]",1,2,0,0,0,0.301030,2.0
13199,133,0,NaN,11,0,r/g,0,80,50,0.0,...,"[273.97, 492.51]","[210.19, 588.02]","[305.76, 593.0]",3,2,0,0,0,0.000000,0.0

In [6]:
conj['run_length'] = conj['runLength'] - 1
conj['run_length'] = conj['run_length'].shift(1)
conj = conj[conj['run_length'].notna()]

In [7]:
conj

,participantN,age,gender,trialN,task,condition,FeatConj,setSize,proportion,timelimit,...,closest_other_target,closest_dist_same_color,closest_dist_same_shape,grouping_selected,grouping_same,grouping_switch,strict_line,blocked_grouped,ratio,run_length
1,1,0,,0,0,rs/gd,1,80,50,0.0,...,"[791.91, 492.55]","[717.25, 506.41]","[829.65, 583.97]",0,0,0,0,0,-0.043466,0.0
2,1,0,,0,0,rs/gd,1,80,50,0.0,...,"[735.4, 580.27]","[717.25, 506.41]","[823.7, 663.99]",0,0,0,0,0,-0.066947,1.0
3,1,0,,0,0,rs/gd,1,80,50,0.0,...,"[735.4, 580.27]","[717.25, 506.41]","[702.66, 662.72]",0,0,0,0,0,-0.091770,2.0
4,1,0,,0,0,rs/gd,1,80,50,0.0,...,"[735.4, 580.27]","[717.25, 506.41]","[702.66, 662.72]",0,0,0,0,0,-0.118099,3.0
5,1,0,,0,0,rs/gd,1,80,50,0.0,...,"[487.21, 587.0]","[366.36, 670.59]","[702.66, 662.72]",0,0,0,0,0,-0.146128,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13155,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,"[297.34, 441.21]","[393.55, 486.93]","[294.81, 579.88]",0,0,0,0,0,0.301030,15.0
13156,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,"[400.08, 651.14]","[393.55, 486.93]","[294.81, 579.88]",0,0,0,0,0,0.176091,16.0
13157,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,"[146.9, 554.92]","[393.55, 486.93]","[226.6, 584.88]",0,0,0,0,0,0.000000,17.0
13158,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,"[469.48, 557.46]","[393.55, 486.93]","[294.81, 579.88]",0,0,0,0,0,-0.301030,18.0
13159,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,"[285.01, 205.82]","[301.73, 124.36]","[140.29, 205.39]",1,4,1,0,0,0.000000,19.0

### Delete '[  ]' from each row in coord coluns (for changing to float)

In [8]:
feat['resp_pos'] = feat['resp_pos'].str[1:-1]
feat['closest_same_target'] = feat['closest_same_target'].str[1:-1]
feat['closest_other_target'] = feat['closest_other_taget'].str[1:-1]
feat['closest_blue_dot'] = feat['closest_blue_dot'].str[1:-1]
feat['closest_yellow_dot'] = feat['closest_yellow_dot'].str[1:-1]

In [9]:
conj['resp_pos'] = conj['resp_pos'].str[1:-1]
conj['closest_same_target'] = conj['closest_same_target'].str[1:-1]
conj['closest_other_target'] = conj['closest_other_target'].str[1:-1]
conj['closest_dist_same_color'] = conj['closest_dist_same_color'].str[1:-1]
conj['closest_dist_same_shape'] = conj['closest_dist_same_shape'].str[1:-1]

### Change type of coord 'str' to 'float'

In [10]:
feat['resp_pos'] = feat['resp_pos'].apply(lambda x: [float(y) for y in x.split(',')])
feat['closest_same_target'] = feat['closest_same_target'].apply(lambda x: [float(y) for y in x.split(',')])
feat['closest_other_target'] = feat['closest_other_target'].apply(lambda x: [float(y) for y in x.split(',')])
feat['closest_blue_dot'] = feat['closest_blue_dot'].apply(lambda x: [float(y) for y in x.split(',')])
feat['closest_yellow_dot'] = feat['closest_yellow_dot'].apply(lambda x: [float(y) for y in x.split(',')])

In [11]:
conj['resp_pos'] = conj['resp_pos'].apply(lambda x: [float(y) for y in x.split(',')])
conj['closest_same_target'] = conj['closest_same_target'].apply(lambda x: [float(y) for y in x.split(',')])
conj['closest_other_target'] = conj['closest_other_target'].apply(lambda x: [float(y) for y in x.split(',')])
conj['closest_dist_same_color'] = conj['closest_dist_same_color'].apply(lambda x: [float(y) for y in x.split(',')])
conj['closest_dist_same_shape'] = conj['closest_dist_same_shape'].apply(lambda x: [float(y) for y in x.split(',')])

### Make columns with coord as np array

In [12]:
feat['cl_same'] = ((np.array(feat['resp_pos'].values.tolist())
                              - np.array(feat['closest_same_target']
                                         .values
                                         .tolist()))**2).sum(axis=1) ** 0.5
feat['cl_other'] = ((np.array(feat['resp_pos'].values.tolist()) 
                                 - np.array(feat['closest_other_target']
                                            .values
                                            .tolist()))**2).sum(axis=1) ** 0.5
feat['cl_blue'] = ((np.array(feat['resp_pos'].values.tolist()) 
                                 - np.array(feat['closest_blue_dot']
                                            .values
                                            .tolist()))**2).sum(axis=1) ** 0.5
feat['cl_yellow'] = ((np.array(feat['resp_pos'].values.tolist()) 
                                 - np.array(feat['closest_yellow_dot']
                                            .values
                                            .tolist()))**2).sum(axis=1) ** 0.5

In [13]:
conj['cl_same'] = ((np.array(conj['resp_pos'].values.tolist())
                              - np.array(conj['closest_same_target']
                                         .values
                                         .tolist()))**2).sum(axis=1) ** 0.5
conj['cl_other'] = ((np.array(conj['resp_pos'].values.tolist()) 
                                 - np.array(conj['closest_other_target']
                                            .values
                                            .tolist()))**2).sum(axis=1) ** 0.5
conj['cl_same_color'] = ((np.array(conj['resp_pos'].values.tolist()) 
                                 - np.array(conj['closest_dist_same_color']
                                            .values
                                            .tolist()))**2).sum(axis=1) ** 0.5
conj['cl_same_shape'] = ((np.array(conj['resp_pos'].values.tolist()) 
                                 - np.array(conj['closest_dist_same_shape']
                                            .values
                                            .tolist()))**2).sum(axis=1) ** 0.5

In [14]:
conj

,participantN,age,gender,trialN,task,condition,FeatConj,setSize,proportion,timelimit,...,grouping_same,grouping_switch,strict_line,blocked_grouped,ratio,run_length,cl_same,cl_other,cl_same_color,cl_same_shape
1,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.043466,0.0,72.458664,120.597315,173.653234,44.679822
2,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.066947,1.0,72.458664,182.400411,234.405408,83.775601
3,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.091770,2.0,73.795082,76.746862,82.512947,105.839343
4,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.118099,3.0,73.795082,103.951828,148.780161,58.197959
5,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.146128,4.0,73.427475,111.076559,194.010000,142.506925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13155,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,0.301030,15.0,100.726603,71.623729,87.982901,69.529062
13156,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,0.176091,16.0,54.503978,116.055368,190.631191,64.136986
13157,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,0.000000,17.0,54.503978,114.601233,218.765058,48.347580
13158,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,-0.301030,18.0,104.503072,72.365282,80.431308,103.741688
13159,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,4,1,0,0,0.000000,19.0,226.072236,76.269919,110.853565,72.729280

#### Drop unuseful columns with coordinates

In [15]:
feat = feat.drop(['closest_same_target', 'closest_other_target', 'closest_other_taget', 'closest_blue_dot', 'closest_yellow_dot'], axis=1)

In [16]:
feat = feat[feat.switches != 2]

In [17]:
conj = conj.drop(['closest_same_target', 'closest_other_target', 'closest_dist_same_color', 'closest_dist_same_shape'], axis=1)

In [18]:
conj = conj[conj.switches != 2]

In [19]:
conj

,participantN,age,gender,trialN,task,condition,FeatConj,setSize,proportion,timelimit,...,grouping_same,grouping_switch,strict_line,blocked_grouped,ratio,run_length,cl_same,cl_other,cl_same_color,cl_same_shape
1,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.043466,0.0,72.458664,120.597315,173.653234,44.679822
2,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.066947,1.0,72.458664,182.400411,234.405408,83.775601
3,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.091770,2.0,73.795082,76.746862,82.512947,105.839343
4,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.118099,3.0,73.795082,103.951828,148.780161,58.197959
5,1,0,,0,0,rs/gd,1,80,50,0.0,...,0,0,0,0,-0.146128,4.0,73.427475,111.076559,194.010000,142.506925
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13155,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,0.301030,15.0,100.726603,71.623729,87.982901,69.529062
13156,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,0.176091,16.0,54.503978,116.055368,190.631191,64.136986
13157,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,0.000000,17.0,54.503978,114.601233,218.765058,48.347580
13158,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,0,0,0,0,-0.301030,18.0,104.503072,72.365282,80.431308,103.741688
13159,133,0,NaN,11,0,rd/gs,1,80,50,0.0,...,4,1,0,0,0.000000,19.0,226.072236,76.269919,110.853565,72.729280

#### Make csv files for 'feat', 'conj', 'feat_conj'

In [20]:
feat.to_csv(r'C:\Users\lttso\Desktop\feat.csv', index = False)

In [21]:
conj.to_csv(r'C:\Users\lttso\Desktop\conj.csv', index = False)

In [22]:
#feat_conj = feat.append(conj, sort=False)

In [23]:
#feat_conj.to_csv(r'C:\Users\User\Desktop\feat_conj.csv', index = False)

#### Filling Na with the -1 value in 'feat_conj'

In [24]:
#both = pd.read_csv(r'C:\Users\User\Desktop\feat_conj.csv')

In [25]:
#both['cl_blue'] = both['cl_blue'].fillna(-1).astype(float)
#both['cl_yellow'] = both['cl_yellow'].fillna(-1).astype(float)
#both['cl_same_color'] = both['cl_same_color'].fillna(-1).astype(float)
#both['cl_same_shape'] = both['cl_same_shape'].fillna(-1).astype(float)

#### Make a final file for 'feat_conj'

In [26]:
#both.to_csv(r'C:\Users\User\Desktop\feat_conj.csv', index = False)